version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: search
      POSTGRES_USER: search
      POSTGRES:DB: search
    ports:
      - 5432:5432

  mongo_db:
    image: 'mongo'
    container_name: 'mongo_service'
    environment:
      - MONGO_INITDB_DATABASE=index
      - MONGO_INITDB_USERNAME=sgudim
      - MONGO_INITROOT_PASSWORD=simon
    volumes:
    - ./mongo-volume:/data/db 
    ports:
      - '27017:27017'