version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: search
      POSTGRES_USER: search
      POSTGRES:DB: search
    ports:
      - 5432:5432